# Methods

UTA provided time point data for all trips on the UVX system during the summer
of 2019. During this period, the TSP requesting threshold was set at three
different levels:

  - June 10 through July 12 and after August 12: 2 minute threshold
  - July 15 through July 26: no TSP
  - July 30 through August 9: TSP always requested

We calculated the headway between successive UVX trips at each stop, as
well as the cumulative dwell time of all stations along the route to that point.
To control for omitted variables, we  limited our analysis to the periods
between 7 AM and 8 PM when the system runs at a 6-minute headway. Time points
within these periods are considered "AM Peak" if occurring between 7 and 9 AM,
or "PM Peak" between 4 and 6 PM. We also discard timepoints in south Provo where
UVX runs on a one-way circulating loop. 

```{r times, eval = FALSE}
tar_load(period_change_table)
period_change_table
```

Standard statistical tests --- such as the student's $t$-test or 
ordinary least squares regression models --- are designed to ascertain the 
significance of a statistic at the *mean* of the distribution. In this
application, we are less concerned with the mean deviation in headway, and are
instead interested in whether TSP is able to reduce the lateness of buses that
already have substantial deviation from their programmed headway. Further, a bus
that is delayed from its intended headway may shorten the subsequent headway due
to "bunching." Consequently, we employ conditional quantile regression
[@koenker2001quantile] to estimate the effect of TSP requesting threshold on
headway deviation at multiple percentiles of the distribution. This is
done with the `quantreg` package for R [@quantreg; @R]

Raw data and complete analysis code are available in a public 
[GitHub repository](https://github.com/byu-transpolab/uvx_headways).