---
title: "The Effect of Transit Signal Priority on Bus Rapid Transit Headway Adherence"
author:
  - name: Gregory Macfarlane
    email: gregmacfarlane@byu.edu
    affiliation: BYU
    footnote: 1
  - name: Grant Schultz
    email: gschultz@byu.edu
    affiliation: BYU
  - name: Michael Sheffield
    email: michael.sheffield@wcg.us
    affiliation: WCG
  - name: Logan Bennett
    email: loganbennett93@gmail.com
    affiliation: BYU
address:
  - code: BYU
    address: Brigham Young University, Civil and Environmental Engineering Department, 430 Engineering Building, Provo, Utah 84602
  - code: WCG
    address: Wall Consultant Group, 9980 S 300 W Ste 200 Sandy, UT 84070
footnote:
  - code: 1
    text: "Corresponding Author"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
journal: "Submitted to Transport Findings"
bibliography: [book.bib]
layout: "3p, authoryear, review"
keywords:
  - Public transit,
  - Transit signal priority,
  - Traffic operations
biblio-style: apalike
link-citations: yes
abstract: |
  We report the results of an experiment to evaluate the impact of transit  signal priority (TSP) on headway adherence for a bus rapid transit (BRT) system in Provo / Orem, Utah. The bus requests TSP based on its unpublished schedule, but users perceive only a headway. Quantile regression models estimated on raw timepoint data from the BRT system reveal that TSP significantly improves headway adherence, after controlling for peak times, direction, and cumulative trip dwell time. We also find that requiring the bus to be 2 minutes late before requesting TSP improves headway adherence more than allowing all buses to request TSP.
description: "An analysis of headways on UVX responding to TSP"
---

# Questions {#intro}

Transit signal priority (TSP) allows traffic signals to flexibly accommodate
transit vehicles. This may involve extending a green phase until the vehicle
passes, triggering an early green if there is a vehicle waiting at the light, or
even running specific transit-only phases. TSP helps transit vehicles maintain
on-time performance [@sheffieldsensitivity; @Liu2018], but often TSP will only engage at a signal if
the vehicle is running behind its schedule, thus minimizing automobile delay
when the bus is otherwise on schedule [@NI20201].

In 2018, the Utah Transit Authority (UTA) launched the Utah Valley Express (UVX) 
Bus Rapid Transit (BRT) system in Provo and Orem, Utah.  The system connects
two commuter rail stations, two major universities (Brigham Young and Utah Valley),
and commercial districts in Orem and Provo. UVX has TSP on 44 of the 47 traffic 
signals along its route. A transit vehicle requests TSP the vehicle is behind its
schedule; the signal controller may then grant the TSP based on a set of rules. 
For example, the signal will not grant TSP to transit vehicles traveling in the 
same direction in consecutive signal cycles. Specifically, at least two "clean" cycles
must run before the signal controller will grant TSP again.

Though the TSP system is based on a schedule, UTA does not publish a schedule
for UVX. Instead informed that a bus will arrive on a specific
headway: 6 minutes in the peak period and 10 minutes in the off-peak. UVX vehicles depart
their initial time point on this schedule, but then proceed to the end of the route 
without consideration as to whether the vehicle is running ahead or behind its "schedule"
as understood by the TSP system. It is
unclear whether the actualized headway is affected by a schedule-based TSP
system, potentially creating frustration for riders or inefficient operations. 
The research questions are therefore:

  - Does schedule-based TSP improve headway adherence for rapid transit systems?
  - What other factors influence headway adherence: direction, dwell time, etc.?


